---
tmux_conf_repo: "https://github.com/suzuki-shunsuke/tmux.conf"
tmux_conf_cloned_dest: "{{ansible_env.HOME}}/repos/src/github.com/suzuki-shunsuke/tmux.conf"
tmux_conf_links:
  - src: "{{(ansible_os_family == 'Darwin')|ternary('mac', 'linux')}}_tmux.conf"
    dest: "{{ansible_env.HOME}}/.tmux.conf"
